export const posterData = [
  {
    id: 1,
    src: '/images/mainpage-length-image.png',
    title: 'The Green Mile',
    year: '2016',
    rating: '9.2',
    genre: 'Biographical',
  },
  {
    id: 2,
    src: '/images/mainpage-length-image.png',
    title: 'The Green Mile',
    year: '2016',
    rating: '9.2',
    genre: 'Biographical',
  },
  {
    id: 3,
    src: '/images/mainpage-length-image.png',
    title: 'The Green Mile',
    year: '2016',
    rating: '9.2',
    genre: 'Biographical',
  },
  {
    id: 4,
    src: '/images/mainpage-length-image.png',
    title: 'The Green Mile',
    year: '2016',
    rating: '9.2',
    genre: 'Biographical',
  },
  {
    id: 5,
    src: '/images/mainpage-length-image.png',
    title: 'The Green Mile',
    year: '2016',
    rating: '9.2',
    genre: 'Biographical',
  },
  {
    id: 6,
    src: '/images/mainpage-length-image.png',
    title: 'The Green Mile',
    year: '2016',
    rating: '9.2',
    genre: 'Biographical',
  },
  {
    id: 6,
    src: '/images/mainpage-length-image.png',
    title: 'The Green Mile',
    year: '2016',
    rating: '9.2',
    genre: 'Biographical',
  },
  {
    id: 6,
    src: '/images/mainpage-length-image.png',
    title: 'The Green Mile',
    year: '2016',
    rating: '9.2',
    genre: 'Biographical',
  },
  {
    id: 6,
    src: '/images/mainpage-length-image.png',
    title: 'The Green Mile',
    year: '2016',
    rating: '9.2',
    genre: 'Biographical',
  },
  {
    id: 6,
    src: '/images/mainpage-length-image.png',
    title: 'The Green Mile',
    year: '2016',
    rating: '9.2',
    genre: 'Biographical',
  },
  {
    id: 6,
    src: '/images/mainpage-length-image.png',
    title: 'The Green Mile',
    year: '2016',
    rating: '9.2',
    genre: 'Biographical',
  },
  {
    id: 6,
    src: '/images/mainpage-length-image.png',
    title: 'The Green Mile',
    year: '2016',
    rating: '9.2',
    genre: 'Biographical',
  },
  {
    id: 6,
    src: '/images/mainpage-length-image.png',
    title: 'The Green Mile',
    year: '2016',
    rating: '9.2',
    genre: 'Biographical',
  },
  {
    id: 6,
    src: '/images/mainpage-length-image.png',
    title: 'The Green Mile',
    year: '2016',
    rating: '9.2',
    genre: 'Biographical',
  },
  {
    id: 6,
    src: '/images/mainpage-length-image.png',
    title: 'The Green Mile',
    year: '2016',
    rating: '9.2',
    genre: 'Biographical',
  },
  {
    id: 6,
    src: '/images/mainpage-length-image.png',
    title: 'The Green Mile',
    year: '2016',
    rating: '9.2',
    genre: 'Biographical',
  },
  {
    id: 6,
    src: '/images/mainpage-length-image.png',
    title: 'The Green Mile',
    year: '2016',
    rating: '9.2',
    genre: 'Biographical',
  },
  {
    id: 6,
    src: '/images/mainpage-length-image.png',
    title: 'The Green Mile',
    year: '2016',
    rating: '9.2',
    genre: 'Biographical',
  },
];
